CE100 Algorithms and Programming II HW3: ce100_hw3_algo_lib_cs.HuffmanCoding Class Reference
ce100_hw3_algo_lib_cs.HuffmanCoding Class Reference
Public Member Functions
Compress
Huffman Coding compress Function
In this method .txt files are compressed.
Parameters
[in] mass [inputFilePath, outputFilePath string] Compress Function
void Compress (string inputFilePath, string outputFilePath)
Compress Music
Huffman Coding compress Function
In this method .MP3 files are compressed.
Parameters
[in] mass [inputFilePath, outputFilePath string] Compress Function
void CompressMusic (string inputFilePath, string outputFilePath)
Decompress
Huffman Coding Decompress Function
In this method .txt files are decompressed.
Parameters
[in] mass [inputFilePath, outputFilePath string] Decompress Function
void Decompress (string inputFilePath, string outputFilePath)
Decompress Music
Huffman Coding Decompress Function
In this method .mp3 files are decompressed.
Parameters
[in] mass [inputFilePath, outputFilePath string] Decompress Function
void DecompressMusic (string inputFilePath, string outputFilePath)
Private Member Functions
Calculate Frequencies
Huffman Coding CalculateFrequencies Function
Method to calculate the frequencies of each character in a string
Parameters
[in] mass [content string] Calculate Frequencies Function
Dictionary< char, int > CalculateFrequencies (string content)
Calculate Frequencies Music
Huffman Coding CalculateFrequenciesMusic Function
Method to calculate the frequencies of each byte in a byte array
Parameters
[in] mass [content string] Calculate Frequencies Function Music
Dictionary< byte, int > CalculateFrequenciesMusic (byte[] content)
Build Huffman Tree
Huffman Coding BuildHuffmanTree Function
Method to build the Huffman tree from a dictionary of character frequencies
Parameters
[in] mass [frequencies Dictionary<char, int>] Build Huffman Tree
HuffmanNode BuildHuffmanTree (Dictionary< char, int > frequencies)
Build Huffman Tree Music
Huffman Coding BuildHuffmanTreeMusic Function
Method to build the Huffman tree from a dictionary of byte frequencies
Parameters
[in] mass [frequencies Dictionary<char, int>] Build Huffman Tree Music
HuffmanNode BuildHuffmanTreeMusic (Dictionary< byte, int > frequencies)
Generate Huffman Codes
Huffman Coding GenerateHuffmanCodes Function
Method to generate Huffman codes for each character using the Huffman tree
Parameters
[in] mass [code string] Generate Huffman Codes
void GenerateHuffmanCodes (HuffmanNode node, string code)
Generate Huffman Codes Music
Huffman Coding GenerateHuffmanCodesMusic Function
Method to generate Huffman codes for each byte using the Huffman tree.
Parameters
[in] mass [code string] Generate Huffman Codes Music
void GenerateHuffmanCodesMusic (HuffmanNode node, string code)
Read Huffman Tree
Huffman Coding ReadHuffmanTree Function
Method to reconstruct the Huffman tree from binary data.
Parameters
[in] mass [binaryReader BinaryReader] Read Huffman Tree
HuffmanNode ReadHuffmanTree (BinaryReader binaryReader)
Read Huffman Tree Music
Huffman Coding ReadHuffmanTreeMusic Function
Method to reconstruct the Huffman tree from binary data for music decompression.
Parameters
[in] mass [binaryReader BinaryReader] Read Huffman Tree Music
HuffmanNode ReadHuffmanTreeMusic (BinaryReader binaryReader)
Convert to String
Huffman Coding ConvertToString Function
Method to convert a byte array into a string of binary digits
Parameters
[in] mass [bytes byte] Convert to String
string ConvertToString (byte[] bytes)
Write Huffman Tree
Huffman Coding WriteHuffmanTree Function
Method to write the Huffman tree to binary data.
Parameters
[in] mass [binaryWriter,node BinaryWriter, HuffmanNode] Write Huffman Tree
void WriteHuffmanTree (BinaryWriter binaryWriter, HuffmanNode node)
Write Huffman Tree Music
Huffman Coding WriteHuffmanTreeMusic Function
Method to write the Huffman tree for music to binary data.
Parameters
[in] mass [binaryWriter,node BinaryWriter, HuffmanNode] Write Huffman Tree Music
void WriteHuffmanTreeMusic (BinaryWriter binaryWriter, HuffmanNode node)
Convert to Bytes
Huffman Coding ConvertToBytes Function
Method to convert a binary string to an array of bytes.
Parameters
[in] mass [binaryWriter,node BinaryWriter, HuffmanNode] Convert to Bytes
byte[] ConvertToBytes (string binaryString)
Private Attributes
Dictionary< char, string > _huffmanCodes = new Dictionary<char, string>()
Define two dictionaries to hold the Huffman codes for characters and mp3 bytes respectively.
Dictionary< byte, string > _huffmanCodesmp3 = new Dictionary<byte, string>()
Member Function Documentation
BuildHuffmanTree()
HuffmanNode ce100_hw3_algo_lib_cs.HuffmanCoding.BuildHuffmanTree (Dictionary< char, int > frequencies) inline private
Create a priority queue of Huffman nodes, each node is associated with a character and its frequency
Continue until there is only one node left in the priority queue (the root of the Huffman tree)
Order the priority queue by frequency
The two nodes with the lowest frequency are combined into a new node
Create a new node with the combined frequency of the two lowest nodes, and these two nodes as its children
Remove the two lowest nodes from the priority queue
Add the new node to the priority queue
Return the remaining node in the priority queue, which is the root of the Huffman tree
References ce100_hw3_algo_lib_cs.HuffmanNode.Frequency.
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.Compress().
BuildHuffmanTreeMusic()
HuffmanNode ce100_hw3_algo_lib_cs.HuffmanCoding.BuildHuffmanTreeMusic (Dictionary< byte, int > frequencies) inline private
Create a priority queue of Huffman nodes, each node is associated with a byte and its frequency
Continue until there is only one node left in the priority queue (the root of the Huffman tree)
Order the priority queue by frequency
The two nodes with the lowest frequency are combined into a new node
Create a new node with the combined frequency of the two lowest nodes, and these two nodes as its children
Remove the two lowest nodes from the priority queue
Add the new node to the priority queue
Return the remaining node in the priority queue, which is the root of the Huffman tree
References ce100_hw3_algo_lib_cs.HuffmanNode.Frequency.
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.CompressMusic().
CalculateFrequencies()
Dictionary<char, int> ce100_hw3_algo_lib_cs.HuffmanCoding.CalculateFrequencies (string content) inline private
Initialize a dictionary to hold the frequencies
Iterate over each character in the string
If the character is already in the dictionary, increment its frequency
If the character is not in the dictionary, add it with a frequency of 1
Return the dictionary of frequencies
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.Compress().
CalculateFrequenciesMusic()
Dictionary<byte, int> ce100_hw3_algo_lib_cs.HuffmanCoding.CalculateFrequenciesMusic (byte[] content) inline private
Initialize a dictionary to hold the frequencies
Iterate over each byte in the byte array
If the byte is already in the dictionary, increment its frequency
If the byte is not in the dictionary, add it with a frequency of 1
Return the dictionary of frequencies
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.CompressMusic().
Compress()
void ce100_hw3_algo_lib_cs.HuffmanCoding.Compress (string inputFilePath, string outputFilePath) inline
Read the content of the input file
Calculate the frequency of each character in the content
Build the Huffman tree based on the calculated frequencies
Generate the Huffman codes from the Huffman tree
Initialize a StringBuilder to hold the compressed data
Append the Huffman code for each character in the content to the compressed data
Calculate the size of the padding needed to make the compressed data a multiple of 8
If padding is needed, append '0's to the compressed data
Open a FileStream to write the compressed data to the output file
Use a BinaryWriter to write to the FileStream
Write the Huffman tree to the output file
Convert the compressed data to bytes
Write the original length of the compressed data (without the padding) to the output file
Write the length of the compressed data bytes to the output file
Write the compressed data bytes to the output file
Write the padding size to the output file
References ce100_hw3_algo_lib_cs.HuffmanCoding._huffmanCodes, ce100_hw3_algo_lib_cs.HuffmanCoding.BuildHuffmanTree(), ce100_hw3_algo_lib_cs.HuffmanCoding.CalculateFrequencies(), ce100_hw3_algo_lib_cs.HuffmanCoding.ConvertToBytes(), ce100_hw3_algo_lib_cs.HuffmanCoding.GenerateHuffmanCodes(), and ce100_hw3_algo_lib_cs.HuffmanCoding.WriteHuffmanTree().
CompressMusic()
void ce100_hw3_algo_lib_cs.HuffmanCoding.CompressMusic (string inputFilePath, string outputFilePath) inline
References ce100_hw3_algo_lib_cs.HuffmanCoding._huffmanCodesmp3, ce100_hw3_algo_lib_cs.HuffmanCoding.BuildHuffmanTreeMusic(), ce100_hw3_algo_lib_cs.HuffmanCoding.CalculateFrequenciesMusic(), ce100_hw3_algo_lib_cs.HuffmanCoding.ConvertToBytes(), ce100_hw3_algo_lib_cs.HuffmanCoding.GenerateHuffmanCodesMusic(), and ce100_hw3_algo_lib_cs.HuffmanCoding.WriteHuffmanTreeMusic().
ConvertToBytes()
byte [] ce100_hw3_algo_lib_cs.HuffmanCoding.ConvertToBytes (string binaryString) inline private
Calculate padding size - how many extra '0's need to be added to the end of the string
to make it a multiple of 8 (length of one byte)
If the padding size is not 8, pad the binary string with '0's on the right
Determine the number of bytes in the binary string
Initialize a byte array of the determined size
Iterate over the binary string in chunks of 8 characters (one byte)
Extract the current chunk of 8 characters
Convert the chunk to a byte and store it in the byte array
Return the byte array
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.Compress(), and ce100_hw3_algo_lib_cs.HuffmanCoding.CompressMusic().
ConvertToString()
string ce100_hw3_algo_lib_cs.HuffmanCoding.ConvertToString (byte[] bytes) inline private
Initialize a StringBuilder with capacity equal to the number of bytes times 8 (since each byte has 8 bits)
For each byte in the input array
Convert the byte to a binary string (base 2), pad with leading zeros to ensure it's always 8 digits long,
and append it to the StringBuilder
Return the binary string
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.Decompress(), and ce100_hw3_algo_lib_cs.HuffmanCoding.DecompressMusic().
Decompress()
void ce100_hw3_algo_lib_cs.HuffmanCoding.Decompress (string inputFilePath, string outputFilePath) inline
Open a FileStream to read the compressed data from the input file
Use a BinaryReader to read from the FileStream
Read the Huffman tree from the input file
Read the original length of the compressed data (without the padding) from the input file
Read the length of the compressed data bytes from the input file
Read the compressed data bytes from the input file
Convert the compressed data bytes to a string and remove any padding
Initialize a StringBuilder to hold the decompressed data
Define a variable to hold the current node in the Huffman tree
Iterate over each bit in the compressed data
If the bit is '0', move to the left child of the current node, otherwise move to the right child
If the current node is a leaf node, append its character to the decompressed data and reset the current node to the root of the Huffman tree
Write the decompressed data to the output file
References ce100_hw3_algo_lib_cs.HuffmanCoding.ConvertToString(), ce100_hw3_algo_lib_cs.HuffmanNode.Left, ce100_hw3_algo_lib_cs.HuffmanCoding.ReadHuffmanTree(), and ce100_hw3_algo_lib_cs.HuffmanNode.Right.
DecompressMusic()
void ce100_hw3_algo_lib_cs.HuffmanCoding.DecompressMusic (string inputFilePath, string outputFilePath) inline
Open a FileStream to read the compressed data from the input file
Use a BinaryReader to read from the FileStream
Read the Huffman tree from the input file
Read the original length of the compressed data (without the padding) from the input file
Read the length of the compressed data bytes from the input file
Read the compressed data bytes from the input file
Convert the compressed data bytes to a string and remove any padding
Initialize a list to hold the decompressed data
Define a variable to hold the current node in the Huffman tree
Iterate over each bit in the compressed data
If the bit is '0', move to the left child of the current node, otherwise move to the right child
If the current node is a leaf node, append its byte to the decompressed data and reset the current node to the root of the Huffman tree
Write the decompressed data to the output file
References ce100_hw3_algo_lib_cs.HuffmanCoding.ConvertToString(), ce100_hw3_algo_lib_cs.HuffmanNode.Left, ce100_hw3_algo_lib_cs.HuffmanCoding.ReadHuffmanTreeMusic(), and ce100_hw3_algo_lib_cs.HuffmanNode.Right.
GenerateHuffmanCodes()
void ce100_hw3_algo_lib_cs.HuffmanCoding.GenerateHuffmanCodes (HuffmanNode node, string code) inline private
If the node is null, return immediately
If the node is a leaf node (i.e., it has no children),
then it represents a character, and we assign the current code to this character
Recursively generate codes for the left and right children,
appending '0' for the left child and '1' for the right child
References ce100_hw3_algo_lib_cs.HuffmanCoding._huffmanCodes, ce100_hw3_algo_lib_cs.HuffmanNode.Character, ce100_hw3_algo_lib_cs.HuffmanNode.Left, and ce100_hw3_algo_lib_cs.HuffmanNode.Right.
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.Compress().
GenerateHuffmanCodesMusic()
void ce100_hw3_algo_lib_cs.HuffmanCoding.GenerateHuffmanCodesMusic (HuffmanNode node, string code) inline private
If the node is null, return immediately
If the node is a leaf node (i.e., it has no children),
then it represents a byte, and we assign the current code to this byte
Recursively generate codes for the left and right children,
appending '0' for the left child and '1' for the right child
References ce100_hw3_algo_lib_cs.HuffmanCoding._huffmanCodesmp3, ce100_hw3_algo_lib_cs.HuffmanNode.Character2, ce100_hw3_algo_lib_cs.HuffmanNode.Left, and ce100_hw3_algo_lib_cs.HuffmanNode.Right.
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.CompressMusic().
ReadHuffmanTree()
HuffmanNode ce100_hw3_algo_lib_cs.HuffmanCoding.ReadHuffmanTree (BinaryReader binaryReader) inline private
If there are no more bytes to read, return null
Read the node type (1 for leaf nodes, other values for internal nodes)
If the node type is 1, it's a leaf node, so we read the character
Read the character from the binary data
Create and return a new leaf node with this character
If the node type is not 1, it's an internal node, so we read the left and right children
Recursively read the left child
Recursively read the right child
Create and return a new internal node with these children
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.Decompress().
ReadHuffmanTreeMusic()
HuffmanNode ce100_hw3_algo_lib_cs.HuffmanCoding.ReadHuffmanTreeMusic (BinaryReader binaryReader) inline private
If there are no more bytes to read, return null
Read the node type (1 for leaf nodes, other values for internal nodes)
If the node type is 1, it's a leaf node, so we read the byte
Read the byte from the binary data
Create and return a new leaf node with this byte
If the node type is not 1, it's an internal node, so we read the left and right children
Recursively read the left child
Recursively read the right child
Create and return a new internal node with these children
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.DecompressMusic().
WriteHuffmanTree()
void ce100_hw3_algo_lib_cs.HuffmanCoding.WriteHuffmanTree (BinaryWriter binaryWriter, HuffmanNode node) inline private
If the node is null, we've reached a leaf node, so return
If the node is a leaf node (both left and right children are null)
Write a byte value of 1 to denote a leaf node
Write the character of this leaf node (convert the character to ushort for writing)
If the node is an internal node (it has at least one child)
Write a byte value of 0 to denote an internal node
Recursively write the left child
Recursively write the right child
References ce100_hw3_algo_lib_cs.HuffmanNode.Character, ce100_hw3_algo_lib_cs.HuffmanNode.Left, and ce100_hw3_algo_lib_cs.HuffmanNode.Right.
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.Compress().
WriteHuffmanTreeMusic()
void ce100_hw3_algo_lib_cs.HuffmanCoding.WriteHuffmanTreeMusic (BinaryWriter binaryWriter, HuffmanNode node) inline private
If the node is null, we've reached a leaf node, so return
If the node is a leaf node (both left and right children are null)
Write a byte value of 1 to denote a leaf node
Write the byte (Character2) of this leaf node
If the node is an internal node (it has at least one child)
Write a byte value of 0 to denote an internal node
Recursively write the left child
Recursively write the right child
References ce100_hw3_algo_lib_cs.HuffmanNode.Character2, ce100_hw3_algo_lib_cs.HuffmanNode.Left, and ce100_hw3_algo_lib_cs.HuffmanNode.Right.
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.CompressMusic().
Field Documentation
_huffmanCodes
Dictionary<char, string> ce100_hw3_algo_lib_cs.HuffmanCoding._huffmanCodes = new Dictionary<char, string>() private
Define two dictionaries to hold the Huffman codes for characters and mp3 bytes respectively.
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.Compress(), and ce100_hw3_algo_lib_cs.HuffmanCoding.GenerateHuffmanCodes().
_huffmanCodesmp3
Dictionary<byte, string> ce100_hw3_algo_lib_cs.HuffmanCoding._huffmanCodesmp3 = new Dictionary<byte, string>() private
Referenced by ce100_hw3_algo_lib_cs.HuffmanCoding.CompressMusic(), and ce100_hw3_algo_lib_cs.HuffmanCoding.GenerateHuffmanCodesMusic().
The documentation for this class was generated from the following file:
ce100-hw3-algo-lib-cs/Class1.cs