CE100 Algorithms and Programming II HW3: ce100_hw3_algo_lib_cs.DisjointSet Class Reference
ce100_hw3_algo_lib_cs.DisjointSet Class Reference
Public Member Functions
DisjointSet (int size)
int Find (int x)
void Union (int x, int y)
Private Attributes
int[] _parent
int[] _rank
Detailed Description
Cod array representing a discrete data structure
Constructor & Destructor Documentation
DisjointSet()
ce100_hw3_algo_lib_cs.DisjointSet.DisjointSet (int size) inline
Prompts to instantiate a new instance of the DisjoinSet class with the desired size
Parameters
size holds the size of the disjoint set
creates _parent and _rank arrays of the specified size
Sets the root of each element equal to itself and sets its rank to 0
References ce100_hw3_algo_lib_cs.DisjointSet._parent, and ce100_hw3_algo_lib_cs.DisjointSet._rank.
Member Function Documentation
Find()
int ce100_hw3_algo_lib_cs.DisjointSet.Find (int x) inline
Allows to find the root of the desired element
Parameters
x is the element whose root will be found
Returns
root of the specified element
References ce100_hw3_algo_lib_cs.DisjointSet._parent, and ce100_hw3_algo_lib_cs.DisjointSet.Find().
Referenced by ce100_hw3_algo_lib_cs.DisjointSet.Find(), and ce100_hw3_algo_lib_cs.DisjointSet.Union().
Union()
void ce100_hw3_algo_lib_cs.DisjointSet.Union (int x, int y) inline
code sequence combining the roots of two elements
Parameters
x first element to be merged
y second element to be merged
Finds the roots of the first and second element
no concatenation if the two roots have the same value
If the rank of the first element is greater than the second, equals the root of the second to the first
If the rank of the first element is less than the second, equals the root of the first to the second
If the ranks are equal, equals the root of the second to the first and increases the rank of the first
References ce100_hw3_algo_lib_cs.DisjointSet._parent, ce100_hw3_algo_lib_cs.DisjointSet._rank, and ce100_hw3_algo_lib_cs.DisjointSet.Find().
Field Documentation
_parent
int [] ce100_hw3_algo_lib_cs.DisjointSet._parent private
Referenced by ce100_hw3_algo_lib_cs.DisjointSet.DisjointSet(), ce100_hw3_algo_lib_cs.DisjointSet.Find(), and ce100_hw3_algo_lib_cs.DisjointSet.Union().
_rank
int [] ce100_hw3_algo_lib_cs.DisjointSet._rank private
Referenced by ce100_hw3_algo_lib_cs.DisjointSet.DisjointSet(), and ce100_hw3_algo_lib_cs.DisjointSet.Union().
The documentation for this class was generated from the following file:
ce100-hw3-algo-lib-cs/Class1.cs