CE100 Algorithms and Programming II HW3: ce100_hw3_algo_lib_cs.IkeaAssemblyGuide Class Reference
ce100_hw3_algo_lib_cs.IkeaAssemblyGuide Class Reference
Public Member Functions
IkeaAssemblyGuide ()
Constructor for the IkeaAssemblyGuide class. It initializes the list of assembly steps.
Add Assembly Step
AddAssemblyStep Method
Method to add an assembly step to the guide. It takes a step ID, a description, and a list of dependencies as arguments.
Parameters
[in] mass [stepId,description,dependencies int, string,List<int>] Add Assembly Step
void AddAssemblyStep (int stepId, string description, List< int > dependencies)
Topological Sort
TopologicalSort Method
Method to add an assembly step to the guide. It takes a step ID, a description, and a list of dependencies as arguments.
Parameters
[in] mass [] Topological Sort
List< int > TopologicalSort ()
Get Assembly Steps Text
GetAssemblyStepsText Method
This method is to get the assembly steps in a proper order (based on their dependencies) in a text format.
Parameters
[in] mass [] Get Assembly Steps Text
List< string > GetAssemblyStepsText ()
Private Member Functions
DFS
DFS Method
This is a private helper method to perform a depth-first search (DFS) from a given step ID.
Parameters
[in] mass [stepId,visited,sortedStack,stepDict int, HashSet<int>,Stack<int>,Dictionary<int, AssemblyStep>] DFS
void DFS (int stepId, HashSet< int > visited, Stack< int > sortedStack, Dictionary< int, AssemblyStep > stepDict)
Private Attributes
List< AssemblyStep > assemblySteps
Define a private list of AssemblyStep objects. This will hold all the assembly steps in the guide.
Constructor & Destructor Documentation
IkeaAssemblyGuide()
ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.IkeaAssemblyGuide () inline
Constructor for the IkeaAssemblyGuide class. It initializes the list of assembly steps.
Initialize the list of assembly steps.
References ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.assemblySteps.
Member Function Documentation
AddAssemblyStep()
void ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.AddAssemblyStep (int stepId, string description, List< int > dependencies) inline
Create a new AssemblyStep object with the provided arguments.
Add the new assembly step to the list of assembly steps.
References ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.assemblySteps.
DFS()
void ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.DFS (int stepId, HashSet< int > visited, Stack< int > sortedStack, Dictionary< int, AssemblyStep > stepDict) inline private
Add the current step ID to the set of visited steps.
Get the current step from the dictionary using the step ID.
Iterate over each dependency of the current step.
If a dependency has not been visited, perform a DFS from that dependency.
After visiting all dependencies of the current step, add the current step ID to the stack.
References ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.DFS().
Referenced by ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.DFS(), and ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.TopologicalSort().
GetAssemblyStepsText()
List< string > ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.GetAssemblyStepsText () inline
Perform a topological sort to get the steps in the order they should be performed.
Initialize a new list to store the steps in text format.
Iterate over the sorted steps in reverse order. This is because the topological sort gives us the steps in reverse order (the last step comes first).
Get the ID of the current step.
Find the step with the current ID in the list of all assembly steps.
Add the description of the current step to the list of step texts, prefixed by "Step {stepId}:".
Return the list of step descriptions in the correct order.
References ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.assemblySteps, and ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.TopologicalSort().
TopologicalSort()
List< int > ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.TopologicalSort () inline
Create a dictionary from the list of assembly steps for easy lookup by step ID.
Create a hash set to keep track of the steps that have been visited during the depth-first search (DFS).
Create a stack to hold the sorted steps. Steps are added to the stack after all their dependencies have been visited.
Iterate over each step in the dictionary. If a step has not been visited, perform a DFS from that step.
Return the steps in the order they should be performed. Since we added steps to the stack after their dependencies,
converting the stack to a list gives the correct order of steps.
References ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.assemblySteps, and ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.DFS().
Referenced by ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.GetAssemblyStepsText().
Field Documentation
assemblySteps
List<AssemblyStep> ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.assemblySteps private
Define a private list of AssemblyStep objects. This will hold all the assembly steps in the guide.
Referenced by ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.AddAssemblyStep(), ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.GetAssemblyStepsText(), ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.IkeaAssemblyGuide(), and ce100_hw3_algo_lib_cs.IkeaAssemblyGuide.TopologicalSort().
The documentation for this class was generated from the following file:
ce100-hw3-algo-lib-cs/Class1.cs