CE100 Algorithms and Programming II HW3: ce100_hw3_algo_lib_cs.PipelineSystem Class Reference
ce100_hw3_algo_lib_cs.PipelineSystem Class Reference
Public Member Functions
PipelineSystem (int numberOfTrees)
List< EdgePS > KruskalMST ()
List< string > GetMSTEdgesTextualDescriptions (List< EdgePS > mstEdges)
Private Member Functions
void GenerateRandomTreeLocations (int numberOfTrees)
void BuildConnections ()
Private Attributes
List< Tree > _trees
List< EdgePS > _edges
Detailed Description
Represents a system that connects trees
Constructor & Destructor Documentation
PipelineSystem()
ce100_hw3_algo_lib_cs.PipelineSystem.PipelineSystem (int numberOfTrees) inline
Runs a piplinesystem instance with the given number of trees
generates the positions of trees in random shapes
makes connections between randomly positioned trees
References ce100_hw3_algo_lib_cs.PipelineSystem._edges, ce100_hw3_algo_lib_cs.PipelineSystem._trees, ce100_hw3_algo_lib_cs.PipelineSystem.BuildConnections(), and ce100_hw3_algo_lib_cs.PipelineSystem.GenerateRandomTreeLocations().
Member Function Documentation
BuildConnections()
void ce100_hw3_algo_lib_cs.PipelineSystem.BuildConnections () inline private
makes connections between randomly positioned trees
Calculate the distance between two trees
References ce100_hw3_algo_lib_cs.PipelineSystem._edges, and ce100_hw3_algo_lib_cs.PipelineSystem._trees.
Referenced by ce100_hw3_algo_lib_cs.PipelineSystem.PipelineSystem().
GenerateRandomTreeLocations()
void ce100_hw3_algo_lib_cs.PipelineSystem.GenerateRandomTreeLocations (int numberOfTrees) inline private
creates a new random object
References ce100_hw3_algo_lib_cs.PipelineSystem._trees.
Referenced by ce100_hw3_algo_lib_cs.PipelineSystem.PipelineSystem().
GetMSTEdgesTextualDescriptions()
List< string > ce100_hw3_algo_lib_cs.PipelineSystem.GetMSTEdgesTextualDescriptions (List< EdgePS > mstEdges) inline
Returns textual descriptions of the edges of the minimum spanning tree (MST).
Parameters
mstEdges List of edges in MST.
Returns
A list of textual descriptions of edges in the MST.
KruskalMST()
List< EdgePS > ce100_hw3_algo_lib_cs.PipelineSystem.KruskalMST () inline
Finds the minimum spanning tree (MST) of the system using Kruskal's algorithm.
Returns
A list of edges representing the MST.
Code sequence that sorts edges by distance
References ce100_hw3_algo_lib_cs.PipelineSystem._edges, ce100_hw3_algo_lib_cs.PipelineSystem._trees, ce100_hw3_algo_lib_cs.EdgePS.Destination, ce100_hw3_algo_lib_cs.Tree.Id, and ce100_hw3_algo_lib_cs.EdgePS.Source.
Field Documentation
_edges
List<EdgePS> ce100_hw3_algo_lib_cs.PipelineSystem._edges private
A list of links between trees in the system
Referenced by ce100_hw3_algo_lib_cs.PipelineSystem.BuildConnections(), ce100_hw3_algo_lib_cs.PipelineSystem.KruskalMST(), and ce100_hw3_algo_lib_cs.PipelineSystem.PipelineSystem().
_trees
List<Tree> ce100_hw3_algo_lib_cs.PipelineSystem._trees private
Keeps a list of trees in the system
Referenced by ce100_hw3_algo_lib_cs.PipelineSystem.BuildConnections(), ce100_hw3_algo_lib_cs.PipelineSystem.GenerateRandomTreeLocations(), ce100_hw3_algo_lib_cs.PipelineSystem.KruskalMST(), and ce100_hw3_algo_lib_cs.PipelineSystem.PipelineSystem().
The documentation for this class was generated from the following file:
ce100-hw3-algo-lib-cs/Class1.cs